[package]
name = "BrouwerFixedPoint"
version = "0.1"
lean_version = "leanprover-community/lean:3.42.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "2aa3fd9489deec10620bc84e87fe12292a80ccf0"}
lean-liquid = {git = "https://github.com/leanprover-community/lean-liquid", rev = "b646a1f131d272c7d994abeff318e626561a666e"}